from yacs.config import CfgNode as CN


CFG = CN()

# VANILA - mlp
CFG.VANILA_MLP = CN()
CFG.VANILA_MLP.HIDDEN_SIZE = 10


# RESIDUAL
CFG.RESIDUAL = CN()
CFG.RESIDUAL.HIDDEN_SIZE = 400
CFG.RESIDUAL.DROP_RATE = 0.05
CFG.RESIDUAL.INIT_METHOD = 'random'

# DPT
CFG.DPT = CN()
CFG.DPT.HIDDEN_SIZE = 10

# DEPT
CFG.DEPT = CN()
CFG.DEPT.R = 30 # Lora attention dimension
CFG.DEPT.ALPHA = 8

