from yacs.config import CfgNode as CN


CFG = CN()

# VANILA - mlp
CFG.VANILA_MLP = CN()
CFG.VANILA_MLP.HIDDEN_SIZE = 10


# RESIDUAL
CFG.RESIDUAL = CN()
CFG.RESIDUAL.HIDDEN_SIZE = 400
CFG.RESIDUAL.DROP_RATE = 0.05
CFG.RESIDUAL.INIT_METHOD = 'random'


# DPT
CFG.DPT = CN()
CFG.DPT.HIDDEN_SIZE = 10

# Shallow DPT
CFG.SHALLOW = CN()
CFG.SHALLOW.SPECIAL_TOKEN_SIZE = 1
CFG.SHALLOW.HIDDEN_SIZE = 100
